
package views;

import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
     * PROYECTO 2 
     * SISTEMAS OPERATIVOS
     * DIANA DECENA Y JOSE ALGUINDIGUE 
 **/
public class VentanaPrincipal extends javax.swing.JFrame {

    private int cont = 3;
    
    
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        start.setVisible(false);
        contador.setVisible(false);
        
        
        Timer timer = new Timer(2000, (ActionEvent ae) -> { 
            proyecto.setVisible(false);
            start.setVisible(true);
            contador.setVisible(true);
            if(cont == 2){
                contador.setIcon(new ImageIcon(getClass().getResource("2.png")));
            }
            if(cont == 1){
                contador.setIcon(new ImageIcon(getClass().getResource("1.png")));
            }
            if(cont == 0){
                this.setVisible(false);
                ColasUI ui = new ColasUI();
                ui.setVisible(true);
            }
            cont--;
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        contador = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        proyecto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/3.png"))); // NOI18N
        jPanel1.add(contador, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, -1, -1));

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/text1.png"))); // NOI18N
        jPanel1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, -1));

        proyecto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/proyecto1.png"))); // NOI18N
        jPanel1.add(proyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/cool-bg-2.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel proyecto;
    private javax.swing.JLabel start;
    // End of variables declaration//GEN-END:variables
}
